version: '3.9'

services:
  general-db:
    image: postgres
    deploy:
      resources:
        limits:
          memory: 200M
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    networks:
      - backend
    volumes:
      - general_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  general_data:

networks:
  backend: