spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres #postgres is DB_name
    username: postgres
    password: mysecretpassword
  jpa:
    properties:
      hibernate:
        temp:
          :use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml #here we give the location of changelog file that store the location of the changesets

#  scheduler:
#    cron:
#      expired-something: 0 31 16 * * ?
#      # s m h M every # at 20:00 on 2nd day of every month these are cron job
#      # https://crontab.guru/

  url:
    ms-notifications: http://localhost:7575/notifications
